// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sada.Api.Entity.Context;

#nullable disable

namespace Sada.Api.Entity.Migrations
{
    [DbContext(typeof(SadaDbContext))]
    partial class SadaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sada.Api.Entity.Model.CidadeModel", b =>
                {
                    b.Property<int>("Id_Cidade")
                        .HasColumnType("int")
                        .HasColumnName("ID_CIDADE");

                    b.Property<string>("Descricao_Cidade")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("DESCRICAO_CIDADE");

                    b.Property<int>("Id_Uf")
                        .HasColumnType("int")
                        .HasColumnName("ID_UF");

                    b.HasKey("Id_Cidade");

                    b.HasIndex("Id_Uf");

                    b.ToTable("TBL_CIDADE", "dbo");
                });

            modelBuilder.Entity("Sada.Api.Entity.Model.SexoModel", b =>
                {
                    b.Property<int>("Id_Sexo")
                        .HasColumnType("int")
                        .HasColumnName("ID_SEXO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("SIGLA");

                    b.HasKey("Id_Sexo");

                    b.ToTable("TBL_SEXO", "dbo");
                });

            modelBuilder.Entity("Sada.Api.Entity.Model.TituloModel", b =>
                {
                    b.Property<int>("IdTitulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTitulo"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("Vencimento")
                        .HasColumnType("datetime2");

                    b.HasKey("IdTitulo");

                    b.ToTable("Titulos");
                });

            modelBuilder.Entity("Sada.Api.Entity.Model.UfModel", b =>
                {
                    b.Property<int>("Id_Uf")
                        .HasColumnType("int")
                        .HasColumnName("ID_UF");

                    b.Property<string>("Sigla")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DESCRICAO_IF");

                    b.Property<string>("Sigla_Uf")
                        .HasColumnType("char(2)")
                        .HasColumnName("SIGLA_UF");

                    b.HasKey("Id_Uf");

                    b.ToTable("TBL_UF", "dbo");
                });

            modelBuilder.Entity("Sada.Api.Entity.Model.UsuarioModel", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("BAIRRO");

                    b.Property<string>("E_MAIL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("E_MAIL");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ENDERECO");

                    b.Property<int?>("ID_SEXO")
                        .HasColumnType("int")
                        .HasColumnName("ID_SEXO");

                    b.Property<int?>("IdCidade")
                        .HasColumnType("int")
                        .HasColumnName("ID_CIDADE");

                    b.Property<int?>("IdUf")
                        .HasColumnType("int")
                        .HasColumnName("ID_UF");

                    b.Property<string>("Login")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("LOGIN");

                    b.Property<string>("NomeSocial")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("NOME_SOCIAL");

                    b.Property<string>("NomeUsuario")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOME_USUARIO");

                    b.Property<string>("NumeroEndereco")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NUMERO");

                    b.Property<string>("Senha")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SENHA");

                    b.HasKey("IdUsuario");

                    b.ToTable("TBL_USUARIO", (string)null);
                });

            modelBuilder.Entity("Sada.Api.Entity.Model.CidadeModel", b =>
                {
                    b.HasOne("Sada.Api.Entity.Model.UfModel", null)
                        .WithMany()
                        .HasForeignKey("Id_Uf")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_CIDADE_TBL_UF");
                });
#pragma warning restore 612, 618
        }
    }
}
